# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    hospital.datos_twig:
        class:      HospitalBundle\Service\DatosTwig
        arguments:  [ @doctrine.orm.default_entity_manager ]
    hospital.maintenance_mode:
        class: HospitalBundle\EventListener\MaintenanceListener
        arguments:
            - @service_container   
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
